"""add ad_signals normalized table

Revision ID: 749c49fe4ea6
Revises: bab39caad30a
Create Date: 2026-09-13 15:55:52.608573+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '749c49fe4ea6'
down_revision: Union[str, None] = 'bab39caad30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_ad_id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('page_name', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('active_days', sa.Integer(), nullable=True),
    sa.Column('reach', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('collation_count', sa.Integer(), nullable=True),
    sa.Column('ad_copy', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('landing_page_url', sa.Text(), nullable=True),
    sa.Column('ad_library_url', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('matched_query', sa.Text(), nullable=True),
    sa.Column('candidate_id', sa.String(length=64), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_ad_id', name='uq_ad_signal_natural')
    )
    op.create_index('ix_ad_signals_active', 'ad_signals', ['source', 'country', 'active_days'], unique=False)
    op.create_index(op.f('ix_ad_signals_last_seen_at'), 'ad_signals', ['last_seen_at'], unique=False)
    op.create_index('ix_ad_signals_page', 'ad_signals', ['page_id'], unique=False)
    op.create_index(op.f('ix_ad_signals_request_id'), 'ad_signals', ['request_id'], unique=False)
    op.create_index('ix_ad_signals_seen', 'ad_signals', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_ad_signals_source'), 'ad_signals', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_signals_source'), table_name='ad_signals')
    op.drop_index('ix_ad_signals_seen', table_name='ad_signals')
    op.drop_index(op.f('ix_ad_signals_request_id'), table_name='ad_signals')
    op.drop_index('ix_ad_signals_page', table_name='ad_signals')
    op.drop_index(op.f('ix_ad_signals_last_seen_at'), table_name='ad_signals')
    op.drop_index('ix_ad_signals_active', table_name='ad_signals')
    op.drop_table('ad_signals')
    # ### end Alembic commands ###
