"""add seller and is_sponsored to ecom_products

Revision ID: 04877f4599c9
Revises: 2144a1eb5d9c
Create Date: 2026-09-13 05:28:58.335630+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04877f4599c9'
down_revision: Union[str, None] = '2144a1eb5d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecom_products', sa.Column('seller', sa.String(length=255), nullable=True))
    op.add_column('ecom_products', sa.Column('is_sponsored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecom_products', 'is_sponsored')
    op.drop_column('ecom_products', 'seller')
    # ### end Alembic commands ###
