"""add relevance score to reddit threads

Revision ID: c0f50a9ed5ef
Revises: 749c49fe4ea6
Create Date: 2026-09-13 16:46:13.829516+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c0f50a9ed5ef'
down_revision: Union[str, None] = '749c49fe4ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_threads', sa.Column('relevance_score', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('reddit_threads', sa.Column('relevance_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_threads', 'relevance_reason')
    op.drop_column('reddit_threads', 'relevance_score')
    # ### end Alembic commands ###
