"""initial schema

Revision ID: 2144a1eb5d9c
Revises: 
Create Date: 2026-09-13 05:07:53.215499+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2144a1eb5d9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=150), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('tokens_prompt', sa.Integer(), nullable=False),
    sa.Column('tokens_completion', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_results_created_at'), 'ai_analysis_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_request_id'), 'ai_analysis_results', ['request_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_target_url'), 'ai_analysis_results', ['target_url'], unique=False)
    op.create_table('ai_provider_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('api_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_audit_logs_created_at'), 'api_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_audit_logs_request_id'), 'api_audit_logs', ['request_id'], unique=False)
    op.create_table('ecom_price_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('external_product_id', sa.String(length=128), nullable=False),
    sa.Column('external_variant_id', sa.String(length=128), nullable=False),
    sa.Column('variant_title', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('price_minor', sa.BigInteger(), nullable=False),
    sa.Column('compare_at_minor', sa.BigInteger(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecom_price_points_external_product_id'), 'ecom_price_points', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_ecom_price_points_observed_at'), 'ecom_price_points', ['observed_at'], unique=False)
    op.create_index(op.f('ix_ecom_price_points_request_id'), 'ecom_price_points', ['request_id'], unique=False)
    op.create_index('ix_price_points_variant', 'ecom_price_points', ['source', 'shop_domain', 'external_variant_id', 'observed_at'], unique=False)
    op.create_table('ecom_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('price_min_minor', sa.BigInteger(), nullable=True),
    sa.Column('price_max_minor', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('sales_volume', sa.Integer(), nullable=True),
    sa.Column('bestseller_rank', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('image_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'shop_domain', 'external_id', name='uq_ecom_product_natural')
    )
    op.create_index(op.f('ix_ecom_products_last_seen_at'), 'ecom_products', ['last_seen_at'], unique=False)
    op.create_index('ix_ecom_products_rating', 'ecom_products', ['source', 'rating'], unique=False)
    op.create_index('ix_ecom_products_seen', 'ecom_products', ['source', 'last_seen_at'], unique=False)
    op.create_index(op.f('ix_ecom_products_shop_domain'), 'ecom_products', ['shop_domain'], unique=False)
    op.create_index(op.f('ix_ecom_products_source'), 'ecom_products', ['source'], unique=False)
    op.create_table('facebook_ads_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('page_id', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('active_status', sa.String(length=20), nullable=False),
    sa.Column('min_date', sa.String(length=10), nullable=True),
    sa.Column('max_date', sa.String(length=10), nullable=True),
    sa.Column('fetch_details', sa.Boolean(), nullable=False),
    sa.Column('total_ads_count', sa.Integer(), nullable=False),
    sa.Column('ads_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_ads_results_created_at'), 'facebook_ads_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_facebook_ads_results_page_id'), 'facebook_ads_results', ['page_id'], unique=False)
    op.create_index(op.f('ix_facebook_ads_results_query'), 'facebook_ads_results', ['query'], unique=False)
    op.create_index(op.f('ix_facebook_ads_results_request_id'), 'facebook_ads_results', ['request_id'], unique=False)
    op.create_table('google_trends_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('geo', sa.String(length=10), nullable=False),
    sa.Column('date_range', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('timeline_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_trends_results_created_at'), 'google_trends_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_google_trends_results_request_id'), 'google_trends_results', ['request_id'], unique=False)
    op.create_table('master_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_prompts_name'), 'master_prompts', ['name'], unique=True)
    op.create_table('provider_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('reddit_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('thread_external_id', sa.String(length=64), nullable=False),
    sa.Column('subreddit', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_reddit_comment_natural')
    )
    op.create_index('ix_reddit_comments_thread', 'reddit_comments', ['thread_external_id', 'score'], unique=False)
    op.create_index(op.f('ix_reddit_comments_thread_external_id'), 'reddit_comments', ['thread_external_id'], unique=False)
    op.create_table('reddit_threads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('subreddit', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('selftext', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('upvote_ratio', sa.Float(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comments_fetched', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_reddit_thread_natural')
    )
    op.create_index(op.f('ix_reddit_threads_posted_at'), 'reddit_threads', ['posted_at'], unique=False)
    op.create_index(op.f('ix_reddit_threads_request_id'), 'reddit_threads', ['request_id'], unique=False)
    op.create_index('ix_reddit_threads_score', 'reddit_threads', ['score'], unique=False)
    op.create_index('ix_reddit_threads_sub', 'reddit_threads', ['subreddit', 'posted_at'], unique=False)
    op.create_index(op.f('ix_reddit_threads_subreddit'), 'reddit_threads', ['subreddit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_threads_subreddit'), table_name='reddit_threads')
    op.drop_index('ix_reddit_threads_sub', table_name='reddit_threads')
    op.drop_index('ix_reddit_threads_score', table_name='reddit_threads')
    op.drop_index(op.f('ix_reddit_threads_request_id'), table_name='reddit_threads')
    op.drop_index(op.f('ix_reddit_threads_posted_at'), table_name='reddit_threads')
    op.drop_table('reddit_threads')
    op.drop_index(op.f('ix_reddit_comments_thread_external_id'), table_name='reddit_comments')
    op.drop_index('ix_reddit_comments_thread', table_name='reddit_comments')
    op.drop_table('reddit_comments')
    op.drop_table('proxies')
    op.drop_table('provider_keys')
    op.drop_index(op.f('ix_master_prompts_name'), table_name='master_prompts')
    op.drop_table('master_prompts')
    op.drop_index(op.f('ix_google_trends_results_request_id'), table_name='google_trends_results')
    op.drop_index(op.f('ix_google_trends_results_created_at'), table_name='google_trends_results')
    op.drop_table('google_trends_results')
    op.drop_index(op.f('ix_facebook_ads_results_request_id'), table_name='facebook_ads_results')
    op.drop_index(op.f('ix_facebook_ads_results_query'), table_name='facebook_ads_results')
    op.drop_index(op.f('ix_facebook_ads_results_page_id'), table_name='facebook_ads_results')
    op.drop_index(op.f('ix_facebook_ads_results_created_at'), table_name='facebook_ads_results')
    op.drop_table('facebook_ads_results')
    op.drop_index(op.f('ix_ecom_products_source'), table_name='ecom_products')
    op.drop_index(op.f('ix_ecom_products_shop_domain'), table_name='ecom_products')
    op.drop_index('ix_ecom_products_seen', table_name='ecom_products')
    op.drop_index('ix_ecom_products_rating', table_name='ecom_products')
    op.drop_index(op.f('ix_ecom_products_last_seen_at'), table_name='ecom_products')
    op.drop_table('ecom_products')
    op.drop_index('ix_price_points_variant', table_name='ecom_price_points')
    op.drop_index(op.f('ix_ecom_price_points_request_id'), table_name='ecom_price_points')
    op.drop_index(op.f('ix_ecom_price_points_observed_at'), table_name='ecom_price_points')
    op.drop_index(op.f('ix_ecom_price_points_external_product_id'), table_name='ecom_price_points')
    op.drop_table('ecom_price_points')
    op.drop_index(op.f('ix_api_audit_logs_request_id'), table_name='api_audit_logs')
    op.drop_index(op.f('ix_api_audit_logs_created_at'), table_name='api_audit_logs')
    op.drop_table('api_audit_logs')
    op.drop_table('ai_provider_keys')
    op.drop_index(op.f('ix_ai_analysis_results_target_url'), table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_request_id'), table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_created_at'), table_name='ai_analysis_results')
    op.drop_table('ai_analysis_results')
    # ### end Alembic commands ###
