"""add run_id to crawl_attempts

Revision ID: 3e20fc8cf23c
Revises: 4a5031aeb39e
Create Date: 2026-09-14 08:12:04.377229+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e20fc8cf23c'
down_revision: Union[str, None] = '4a5031aeb39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_attempts', sa.Column('run_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_crawl_attempts_run_id'), 'crawl_attempts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_attempts_run_id'), table_name='crawl_attempts')
    op.drop_column('crawl_attempts', 'run_id')
    # ### end Alembic commands ###
