"""add metric snapshots and crawl watchlist

Revision ID: bab39caad30a
Revises: 04877f4599c9
Create Date: 2026-09-13 05:38:34.099761+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bab39caad30a'
down_revision: Union[str, None] = '04877f4599c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_watchlist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('country_path', sa.String(length=16), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_job_id', sa.String(length=64), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'target', 'country_path', name='uq_watchlist_target')
    )
    op.create_index('ix_watchlist_due', 'crawl_watchlist', ['enabled', 'last_run_at'], unique=False)
    op.create_table('product_metric_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('external_product_id', sa.String(length=128), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('bestseller_rank', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_snap_observed', 'product_metric_snapshots', ['observed_at'], unique=False)
    op.create_index('ix_metric_snap_product', 'product_metric_snapshots', ['source', 'shop_domain', 'external_product_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_product_metric_snapshots_observed_at'), 'product_metric_snapshots', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_metric_snapshots_observed_at'), table_name='product_metric_snapshots')
    op.drop_index('ix_metric_snap_product', table_name='product_metric_snapshots')
    op.drop_index('ix_metric_snap_observed', table_name='product_metric_snapshots')
    op.drop_table('product_metric_snapshots')
    op.drop_index('ix_watchlist_due', table_name='crawl_watchlist')
    op.drop_table('crawl_watchlist')
    # ### end Alembic commands ###
