"""add crawl_source_policies and crawl_attempts

Revision ID: 4a5031aeb39e
Revises: c0f50a9ed5ef
Create Date: 2026-09-14 04:12:10.312995+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4a5031aeb39e'
down_revision: Union[str, None] = 'c0f50a9ed5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=64), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_attempts_created_at'), 'crawl_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawl_attempts_outcome'), 'crawl_attempts', ['outcome'], unique=False)
    op.create_index(op.f('ix_crawl_attempts_request_id'), 'crawl_attempts', ['request_id'], unique=False)
    op.create_index(op.f('ix_crawl_attempts_source'), 'crawl_attempts', ['source'], unique=False)
    op.create_table('crawl_source_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tier_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('min_delay_ms', sa.Integer(), nullable=False),
    sa.Column('jitter_ms', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('identity_max_requests', sa.Integer(), nullable=True),
    sa.Column('identity_max_age_s', sa.Integer(), nullable=True),
    sa.Column('soft_block_cooldown_s', sa.Integer(), nullable=False),
    sa.Column('respect_retry_after', sa.Boolean(), nullable=False),
    sa.Column('daily_budget_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_source_policies_source'), 'crawl_source_policies', ['source'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_source_policies_source'), table_name='crawl_source_policies')
    op.drop_table('crawl_source_policies')
    op.drop_index(op.f('ix_crawl_attempts_source'), table_name='crawl_attempts')
    op.drop_index(op.f('ix_crawl_attempts_request_id'), table_name='crawl_attempts')
    op.drop_index(op.f('ix_crawl_attempts_outcome'), table_name='crawl_attempts')
    op.drop_index(op.f('ix_crawl_attempts_created_at'), table_name='crawl_attempts')
    op.drop_table('crawl_attempts')
    # ### end Alembic commands ###
